site_name: Uniform Code of Military Justice
theme:
  name: readthedocs
  logo: images/logo.png
  features:
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - content.full-width
  extra:
    logo_text: "United Army"
nav:
  - Home: index.md
extra_css:
  - stylesheets/logo.css
  - stylesheets/hide-footer.css
  - stylesheets/wide-table.css
  - stylesheets/wide-layout.css
extra:
  generator: false
  include_cname: true
plugins:
  - search
  - mermaid2
markdown_extensions:
  - admonition
  - toc