site_name: United Army Military Law
theme:
  name: readthedocs
  logo: images/logo.png
  features:
      - navigation.expand
      - navigation.sections
      - navigation.tabs
      - content.full-width
  extra:
      logo_text: "United Army"
nav:
  - Home: index.md
  - General Provisions: general-provisions.md
  - Crimes and Offenses: crimes-and-offenses.md
  - Sentencing & Enforcement: sentencing-enforcement.md
  - Rank Authority: rank-authority.md
  - Rights of Members: rights.md
  - Command & Reporting: command-reporting.md
  - JAGC & Appendecies: jagc.md
  - Pardons & Amnesty Policy: pardons-amnesty.md
  - Conflict of Interest & Recusal: coi-recusal.md
  - Admin Commands: admin.md
  - Leave of Absence: leave-of-absence.md
  - Links: links.md
extra_css:
  - stylesheets/logo.css
  - stylesheets/hide-footer.css
  - stylesheets/wide-table.css
  - stylesheets/wide-layout.css
extra:
  generator: false
  include_cname: true
plugins:
  - search
  - mermaid2
markdown_extensions:
  - admonition
  - toc