name: Notify Discord on Pages Deploy

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord webhook
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST "$DISCORD_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d '{
              "content": "A change to law.krownca.com has been deployed",
              "embeds": [
                {
                  "title": "Details",
                  "description": "The latest changes have been deployed to GitHub Pages.",
                  "color": 3066993,
                  "fields": [
                    {
                      "name": "Repository",
                      "value": "${{ github.repository }}",
                      "inline": true
                    },
                    {
                      "name": "Branch",
                      "value": "${{ github.ref }}",
                      "inline": true
                    }
                  ],
                  "footer": {
                    "text": "GitHub Actions"
                  }
                }
              ]
            }'