name: Notify Discord on Pages Deploy

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord webhook
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST "$DISCORD_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d '{
              "content": "A change to law.krownca.com has been deployed",
              "embeds": [
                {
                  "title": "Details",
                  "description": "The latest changes have been deployed to https://law.krownca.com",
                  "url": "https://law.krownca.com",
                  "color": 3066993,
                  "fields": [
                    {
                      "name": "Overview",
                      "value": "Added Tier II crime of Abandonment of Duties, as well as the following sections:\n\n- Conflict of Interest & Recusal\n- Admin Commands\n- Leave of Absence\n- Pardons & Amnesty Policy\n\nSee these changes at [law.krownca.com](https://law.krownca.com).",
                    }
                  ],
                  "footer": {
                    "text": "law.krownca.com Deployment Handler"
                  }
                }
              ]
            }'